### ISSUE TITLE
Fedora review requests

### ISSUE THREAD

**Issue by jamesjer** [meelgroup/breakid#1]
I am trying to get breakid into the Fedora Linux distribution.  To do so, the package has to pass a review.  The reviewer asked me to make a few requests of you.  None of these are mandatory, but would help us.
- Could you add license headers to files missing them, to give us more confidence that we understand the licensing situation?  Files missing license headers:
    - breakidConfig.cmake.in
    - cmake/cmake_uninstall.cmake.in
    - src/breakid_c.cpp
    - src/breakid_c.h
- Could you remove files that are not needed by breakid?  For example, most of the cmake/Find* files are not needed.  That reduces the number of files we have to analyze for licensing purposes.
- The `DEF_INSTALL_CMAKE_DIR` definition in CMakeLists.txt refers to a `lib` directory.  On RedHat-based systems like Fedora, that should be `lib` for 32-bit systems and `lib64` for 64-bit systems.  Are you willing to use `LIB_INSTALL_DIR` instead of a hard-coded `lib`?

**Comment by msoos** [comment]
Wow, it'd be super-cool if it got packaged! Sorry, I got distracted today.  I'd be very happy to make those changes. Give me a day or two and it should be done, hopefully by tomorrow! 

Let me also ping @JoD who is the original author of BreakID, I just tried cleaning it up, fixing some memory loss issues with the underlying isomorphism algorithm, and created an API for it.

**Comment by msoos** [comment]
Hi!

First of all, thank you so much for wiling to package this for Fedora, that's great news! I have made the required changes. Regarding `lib` vs. `lib64`, I have done what I think others in libwebsocket have done: there is now an option you can pass, `LIB_SUFFIX` that is normally empty. If you set it to 64, it should do what you need :) Let me know if this helped, or if you found something else missing/incorrect/imperfect/etc. Thank you again for the work in advance and thanks for the helpful feedback about how to improve BreakID in terms of it being packaged, it was actually useful! Cheers,

Mate

**Comment by msoos** [comment]
Oh, I just realized that I forgot to add a nice binary that runs the library on a CNF that is nicely named and is installed -- currently, this is just a library. We should have a binary that runs it on a CNF. Let me do that tonight, so it's a lot more usable to the people who install the package and expect to have a binary to be instantly usable. Sorry this hasn't been the case.

Please wait until tonight so I can add that in and it can be packaged in a way that's more usable and provides more value to those installing the package.

**Comment by jamesjer** [comment]
Sure thing.  Thank you for the quick action on all of those items.  I appreciate it.

FYI, once the BreakID package passes review, I intend to also update cryptominisat to 5.11.15.  We've been stuck on 5.8.0 for a long time because cvc5 (and cvc4 before it) wasn't ready for the update.  But it finally is ready, so Fedora 40 will have cryptominisat 5.11.15 with BreakID support, and cvc5, stp, and yices will all use the newer cryptominisat.

**Comment by msoos** [comment]
Hi,

I have now added a pretty full-featured binary. It uses `argparse.hpp`, which has its own MIT license, as indicated in its header. The binary is installed in the appropriate place, and uses the library. I suggest that you don't cut this into two packages i.e. a library and a binary package, however, it's your call. The generated binary also has an associated manpage that is also appropriately installed.

I hope the above helped. Let me know if you need any help and thanks a lot in advance for your work,

Mate

**Comment by msoos** [comment]
> Sure thing. Thank you for the quick action on all of those items. I appreciate it.
> 
> FYI, once the BreakID package passes review, I intend to also update cryptominisat to 5.11.15. We've been stuck on 5.8.0 for a long time because cvc5 (and cvc4 before it) wasn't ready for the update. But it finally is ready, so Fedora 40 will have cryptominisat 5.11.15 with BreakID support, and cvc5, stp, and yices will all use the newer cryptominisat.

Oh nice, sorry, I didn't see this. Thank you so much for packaging all those! I owe you a beer or two. If you come to CCC (Chaos Computer Congress, usually in Hamburg/Leipzig in December) next year, hit me up, would be nice to chat.

Mate

**Comment by jamesjer** [comment]
> Oh nice, sorry, I didn't see this. Thank you so much for packaging all those! I owe you a beer or two. If you come to CCC (Chaos Computer Congress, usually in Hamburg/Leipzig in December) next year, hit me up, would be nice to chat.

Sadly, my employer is unlikely to send me to any conferences.  My work for Fedora is a hobby, not anything I get paid to do.  I can sometimes get a little time off for online conferences, but going in person doesn't seem to be in the cards.

I would like to ask for one more favor.  The versioning is a bit confusing.  The "About" section of https://github.com/meelgroup/breakid says "BreakID 2.3".  README.md has "BreakID 3.0" at the top.  Line 228 of CMakeLists.txt says:
```
set(BREAKID_FULL_VERSION "1.0.0")
```
So, which is it, 1.0.0, 2.3, or 3.0?  Thanks.

**Comment by msoos** [comment]
Hi,

Oh, sad, regarding CCC. I rarely go to Utah, but if I do, I'll keep you in mind :)

Regarding versioning, ooops -- good point! Sorry about that. I now did a release, and called it 3.1.0. I have also fixed the different version names all over the place :) I have also created a build pipeline and it now builds for Linux, Mac, and Windows. So that should help with compatibility in packaging, hopefully :)

Thanks again for spotting this,

Mate

**Comment by jamesjer** [comment]
Thank you for the release!  That will make things easier for me.  However, for some reason the cmake files are now installed into a directory named "libwebsockets".  Line 328 of CMakeLists.txt:
```
   set(DEF_INSTALL_CMAKE_DIR lib${LIB_SUFFIX}/cmake/libwebsockets)
```
A copy and paste error, perhaps?

**Comment by msoos** [comment]
OOhh, great catch! That would have been a bummer. Thank you so much. Fixed now, created new release too. It was introduced when I tried fixing the `lib` vs `lib64` issue. I really need some tests to catch stuff like this. Sorry again.

**Comment by jamesjer** [comment]
The BreakID package passed review today.  I have built it, and updated cryptominisat to version 5.11.15 with BreakID support.  This will all be available when Fedora 40 is released in about 3 months.  Thanks for all of your quick action!

**Comment by msoos** [comment]
Nice, thanks!!!
